# Generated by Django 5.0.4 on 2024-05-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='cIm',
            new_name='crm',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='cmail',
            new_name='email',
        ),
    ]
